### ISSUE TITLE
Bench bot merge can break weights when they have been renamed/added on master

### ISSUE THREAD

**Issue by seadanda** [paritytech/command-bot-scripts#64]
Bench bot merges master before adding its bench on top, but **after** the bench has already been run.
If functions are renamed or added in a pallet the runtime depends on, and the PR is merged to `master` while the bench is running the commit that is added by bench bot after the merge clobbers the changed function's weight.

See https://github.com/paritytech/polkadot-sdk/pull/2913 for an example of this happening. In https://github.com/paritytech/polkadot-sdk/pull/2913/commits/05ce970bd96043adb81d1711e59fd4c8cac84234#diff-f4c624bcbd64d00442a66f742b99178dbc1b873a706ed7f747563aea37576edcL333 the `universal_origin` function is clobbered.

I don't think this should be expected behaviour.
Would it be better to either:

1. Do not merge master as part of the benchmark
2. Instead of benchmark->merge master->commit to branch, change the order to merge master->benchmark->commit to branch

Both of these solutions end up with a bench bot not breaking the branch, and if the new weight needs to be generated after the bench bot has finished running then the PR author can decide to do so, merging master if necessary.

Happy to implement whatever the outcome is if necessary.

**Comment by mordamax** [comment]
@seadanda there's already an option to skip merging, but it wasn't documented `bot bench -v UPSTREAM_MERGE=n`
I've added a note here https://github.com/paritytech/command-bot-scripts/pull/65

Would that help to prevent/solve it?

Not sure how often that may happen, may be better though to flip this merge behavior to not do this by default and optionally enabled this `UPSTREAM_MERGE=y`

lmk, or just suggest commits in the PR above 👌

**Comment by seadanda** [comment]
Ah I didn't know that option existed, personally I think flipping the default would be preferable, I'm not aware of a workflow that would **require** a merge to be done after a bench, but it's great to have an option for people to auto merge if it's their personal preference.

**Comment by mordamax** [comment]
@seadanda could you please specify where it's happening `after a bench`

I see that merge master happens before the bench command https://github.com/paritytech/command-bot-scripts/blob/main/commands/bench/bench.sh#L71 

and later, after bench there's a rebase from its own branch https://github.com/paritytech/command-bot-scripts/blob/main/commands/bench/bench.sh#L138

**Comment by seadanda** [comment]
In the PR I linked above you can see that the bench bot somehow committed the wrong set of weights back to the branch - this could only have happened if it ran on the out of date code.

The other way I suppose would be that master was broken at that commit, but the short-benchmarks CI job should have caught that. I'll dig a bit more tomorrow, you're right that the code you've linked seems to be doing the sane thing.
